export const carCompanies = [
  "Toyota",
  "Volkswagen",
  "General Motors",
  "Ford",
  "Honda",
  "Nissan",
  "BMW",
  "Mercedes-Benz",
  "Hyundai",
  "Tesla",
  "Fiat Chrysler Automobiles (FCA)",
  "Renault",
  "Volvo",
  "Audi",
  "Kia",
  "Mitsubishi",
  "Subaru",
  "Porsche",
  "Jaguar Land Rover",
  "Mazda",
  "Lexus",
  "Chevrolet",
  "Buick",
  "Cadillac",
  "GMC",
  "Jeep",
  "Ram",
  "Ferrari",
  "Maserati",
  "McLaren",
  "Bugatti",
  "Lamborghini",
  "Aston Martin",
  "Rolls-Royce",
  "Bentley",
  "Alfa Romeo",
  "Daimler AG",
  "Peugeot",
  "Citroën",
  "Opel",
  "Vauxhall",
  "Fiat",
  "Abarth",
  "Jeep",
  "Chrysler",
  "Dodge",
  "Alfa Romeo",
  "Maserati",
  "Fiat Professional",
  "Smart",
];
export const carTypes = ["automatic", "manual"];
export const fuelTypes = ["petrol", "diesel", "electric"];
